cluster:
  mkdir -p logs/{rule} &&
  sbatch --parsable
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.time}
    --job-name=smk-{rule}
    --output=logs/{rule}/%j-{rule}.out
    {resources.extra_options}
default-resources:
  # - account=zhzhang_gibh
  - partition=cv2,cv3,cp2,fat
  - qos=normal
  - time="59:59"
  - mem="8G"
  - cpus_per_task=1
  - extra_options=""

scheduler: greedy
use-conda: False
local-cores: 2
keep-going: False
latency-wait: 300
restart-times: 0
printshellcmds: True
cluster-cancel: "scancel"
cluster-status: "slurm-status"
rerun-incomplete: True
max-jobs-per-second: 50
max-status-checks-per-second: 10
